export const guitars = [
  {
    id:1,
    category:'electric',
    brand: 'Gibson',
    img: './img/gibson.png',
    type:'Eléctrico',
    price: 400,
  },

  {
    id:2,
    category:'electric',
    brand: 'Fender',
    img: './img/fender.png',
    type:'Eléctrico',
    price: 500,
  },
  {
    id:3,
    top:'top',
    category:'electric',
    brand: 'Ibanez',
    img: './img/ibanez.png',
    type:'Eléctrico',
    price: 500,
  },
 {
    id:4,
    category:'electric',
    brand: 'Esp LTD',
    img: './img/esp.png',
    type:'Eléctrico',
    price: 500,
  },
  {
    id:5,
    top:'top',
    category:'electric',
    brand: 'EVH Edition',
    img: './img/evh.png',
    type:'Eléctrico',
    price: 500,
  }, 
  {
    id:6,
    top:'top',
    category:'electric',
    brand: 'Gibson SG',
    img: './img/gibsonyoung.png',
    type:'Eléctrico',
    price: 500,
  },
  /* ------Acusticas----- */
  {
    id:7,
    category:'acustic',
    brand: 'Jasmine',
    img: './img/acust_jasmine.png',
    type:'Instrumento acústico',
    price: 500,
  },
  {
    id:8,
    category:'acustic',
    brand: 'Ibanez',
    img: './img/acust_ibanez.png',
    type:'Instrumento acústico',
    price: 500,
  },
  {
    id:9,
    category:'acustic',
    brand: 'Yamaha',
    img: './img/acustic_yamaha.png',
    type:'Instrumento acústico',
    price: 500,
  }, 
  {
    id:10,
    top:'top',
    category:'acustic',
    brand: 'Takamine',
    img: './img/acust_takamine.png',
    type:'Instrumento acústico',
    price: 500,
  }, 
  {
    id:11,
    category:'acustic',
    brand: 'Ibanez AEG',
    img: './img/acust_taylor.png',
    type:'Instrumento acústico',
    price: 500,
  },
  {
    id:12,
    category:'acustic',
    brand: 'Fender',
    img: './img/acust_fender.png',
    type:'Instrumento acústico',
    price: 500,
  },
  /* -----Otros instrumentos */
  {
    id:13,
    top:'top',
    category:'others',
    brand: 'Casio F-91',
    img: './img/casio.png',
    type:'Electrónico',
    price: 500,
  }, 
  {
    id:14,
    category:'others',
    brand: 'Marshall',
    img: './img/marshall.png',
    type:'Amplificador',
    price: 500,
  }, 
  {
    id:15,
    top:'top',
    category:'others',
    brand: 'Bateria',
    img: './img/drum.png',
    type:'Instrumento de percusión',
    price: 500,
  }, 
  {
    id:16,
    category:'others',
    brand: 'Acordeon',
    img: './img/acordeon.png',
    type:'Instrumento de viento',
    price: 500,
  }, 
  {
    id:17,
    category:'others',
    brand: 'Clarinete',
    img: './img/clarinete.png',
    type:'Instrumento de viento',
    price: 500,
  }, 
  {
    id:18,
    category:'others',
    brand: 'Saxofón',
    img: './img/saxofon.png',
    type:'Instrumento de viento',
    price: 500,
  }, 

  
]