export const guitars = [
  {
    id:1,
    category:'electric',
    brand: 'Gibson',
    img: './img/gibson.png',
    type:'Electric',
    price: 400,
    icon:'./img/guitar_icon.png',
  },

  {
    id:2,
    category:'electric',
    brand: 'Paul.T Edition',
    img: './img/paul_timmons_guitar.png',
    type:'Electric',
    price: 1000,
    icon:'./img/guitar_icon.png',
  },
  {
    id:3,
    top:'top',
    category:'electric',
    brand: 'Ibanez',
    img: './img/ibanez.png',
    type:'Electric',
    price: 600,
    icon:'./img/guitar_icon.png',
  },
 {
    id:4,
    category:'electric',
    brand: 'Esp LTD',
    img: './img/esp.png',
    type:'Electric',
    price: 350,
    icon:'./img/guitar_icon.png',
  },
  {
    id:5,
    top:'top',
    category:'electric',
    brand: 'EVH Edition',
    img: './img/evh.png',
    type:'Electric',
    price: 400,
    icon:'./img/guitar_icon.png',
  }, 
  {
    id:6,
    top:'top',
    category:'electric',
    brand: 'Gibson SG',
    img: './img/gibsonyoung.png',
    type:'Electric',
    price: 300,
    icon:'./img/guitar_icon.png',
  },
  /* ------Acusticas----- */
  {
    id:7,
    category:'acustic',
    brand: 'Jasmine',
    img: './img/acust_jasmine.png',
    type:'Acoustic',
    price: 400,
    icon:'./img/acoustic_icon.png',
  },
  {
    id:8,
    category:'acustic',
    brand: 'Ibanez',
    img: './img/acust_ibanez.png',
    type:'Acoustic',
    price: 200,
    icon:'./img/acoustic_icon.png',
  },
  {
    id:9,
    category:'acustic',
    brand: 'Yamaha',
    img: './img/acustic_yamaha.png',
    type:'Acoustic',
    price: 300,
    icon:'./img/acoustic_icon.png',
  }, 
  {
    id:10,
    top:'top',
    category:'acustic',
    brand: 'Takamine',
    img: './img/acust_takamine.png',
    type:'Acoustic',
    price: 350,
    icon:'./img/acoustic_icon.png',
  }, 
  {
    id:11,
    category:'acustic',
    brand: 'Ibanez AEG',
    img: './img/ibanez_aeg.png',
    type:'Acoustic',
    price: 500,
    icon:'./img/acoustic_icon.png',
  },
  {
    id:12,
    category:'acustic',
    brand: 'Fender',
    img: './img/acust_fender.png',
    type:'Acoustic',
    price: 600,
    icon:'./img/acoustic_icon.png',
  },
  /* -----Otros instrumentos */
  {
    id:13,
    top:'top',
    category:'others',
    brand: 'Casio F-91',
    img: './img/casio.png',
    type:'Electronic',
    price: 800,
    icon:'./img/piano_icon.png',
  }, 
  {
    id:14,
    category:'others',
    brand: 'Marshall',
    img: './img/marshall.png',
    type:'Amplificador',
    price: 500,
    icon:'./img/ampli_icon.png',
  }, 
  {
    id:15,
    top:'top',
    category:'others',
    brand: 'Bateria',
    img: './img/drum.png',
    type:'Percusión',
    price: 600,
    icon:'./img/drum_icon.png',
  }, 
  {
    id:16,
    category:'others',
    brand: 'Acordeon',
    img: './img/acordeon.png',
    type:'Instrumento de viento',
    price: 500,
    icon:'./img/acordeon_icon.png',
  }, 
  {
    id:17,
    category:'others',
    brand: 'Clarinete',
    img: './img/clarinete.png',
    type:'Instrumento de viento',
    price: 300,
    icon:'./img/clarinete_icon.png',
  }, 
  {
    id:18,
    category:'others',
    brand: 'Saxofón',
    img: './img/saxofon.png',
    type:'Instrumento de viento',
    price: 450,
    icon:'./img/saxo_icon.png',
  }, 

  
]